In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,recall_score,confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier



In [15]:
data = pd.read_csv('cdd.csv')

In [53]:
data.head(10)

Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -1.000000  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
5     2 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
6     4  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
7     7 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118  1.120631   
8     7 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818  0.370145   
9     9 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   
5  0.260314 -0.568671  ... -0.208254 -0.559825 -0.026398 -0.371427 -0.232794   
6  0.081213  0.464960  ... -0.167716 -0.270710 -0.154104 -0.780055  0.750137   
7 -3.807864  0.615375  ...  1.943465 -1.015455  0.057504 -0.649709 -0.415267   
8  0.851084 -0.392048  ... -0.073425 -0.268092 -0.204233  1.011592  0.373205   
9  0.069539 -0.736727  ... -0.246914 -0.633753 -0.120794 -0.385050 -0.069733   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      1  
1  0.125895 -0.008983  0.014724    2.69      1  
2 -0.139097 -0.055353 -0.059752  378.66      1  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      1  
5  0.105915  0.253844  0.081080    3.67      0  
6 -0.257237  0.034507  0.005168    4.99      1  
7 -0.051634 -1.206921 -1.085339   40.80      1  
8 -0.384157  0.011747  0.142404   93.20      0  
9  0.094199  0.246219  0.083076    3.68      0  

[10 rows x 31 columns]

In [19]:
				X = data.drop('Class', axis=1)
y = data['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

		

0         1         2         3         4         5         6   \
0    1.482642  1.149294 -0.963363 -1.061875 -1.082187  0.078488  0.213996   
1   -0.966391  0.827312 -0.406372 -0.226667  0.302218  0.188323  0.535589   
2   -1.159012 -1.352571 -0.324031 -1.132140 -0.941628  2.281043  1.813316   
3    0.684643  0.289807 -1.988514  0.256462  0.992937 -1.207302 -0.239764   
4    0.657125  1.042757 -1.150522  0.533546 -0.589061 -1.278356 -0.626061   
..        ...       ...       ...       ...       ...       ...       ...   
154  0.161815 -0.226330 -0.340356  1.364877 -0.190968 -0.348030  0.040736   
155 -1.434184 -1.978730 -0.623845  0.814325  1.069582 -0.013798  0.287301   
156 -0.113357  0.909280 -0.047035 -0.234693  0.859042 -0.099786 -0.528681   
157  1.400090 -0.046227 -1.252272  0.982613 -1.981673 -0.841947 -0.181819   
158  0.134298  0.310383  1.994629 -2.212724  0.920476  0.787311 -1.811337   

           7         8         9   ...        20        21        22  \
0   -1.184101  0.261209 -1.103725  ...  0.303355  0.154274  0.412689   
1   -0.635054  0.547557  0.460301  ... -0.371852 -0.247009  0.221750   
2   -0.344575  1.119662  0.090068  ... -0.401267 -1.315162 -1.306881   
3   -0.659416  0.141127  1.401625  ...  1.755280  0.923913  0.873566   
4   -1.801562  0.046261 -0.305736  ... -0.761263 -0.398418  0.135728   
..        ...       ...       ...  ...       ...       ...       ...   
154 -0.670144  0.582471  1.636399  ... -0.364341  0.232251  1.334454   
155 -0.796105 -2.407376  0.997656  ... -3.431559  2.359493  0.412498   
156 -0.072093 -0.083038  0.211535  ... -0.168542 -0.212486  0.139296   
157  0.008886 -0.492581 -2.576892  ... -0.459180 -0.019659  1.467474   
158  1.498234 -0.966447  0.448436  ...  1.582082 -0.702703  0.038096   

           23        24        25        26        27        28        29  
0   -0.572103 -2.996167  1.059470 -0.095209 -0.024222  0.055783 -0.304042  
1    0.640728 -1.125021 -0.155034  0.908261  0.072967  0.120668 -0.301359  
2    2.751651  1.497104  0.358490  0.421564  1.664676  0.152091 -0.400788  
3   -1.280456  0.547598  0.151434 -0.479113 -0.052086  0.501353  1.920402  
4    0.312418  0.564222 -0.511560  2.511319 -0.058423  0.209417 -0.248860  
..        ...       ...       ...       ...       ...       ...       ...  
154 -0.119086  0.096292 -0.990701  1.192459  0.118046  0.239548 -0.294929  
155  3.199689 -0.109266 -0.987097 -0.414786 -0.448737  0.003970 -0.107614  
156  0.015392  0.589850  1.133600 -0.636463  0.052510  0.184079 -0.270021  
157  0.515600  0.211846 -1.495053 -0.742914 -0.755891 -1.379155  0.288279  
158  0.431873  0.829034 -1.386846 -0.947573  0.558967 -0.698105 -0.401345  

[159 rows x 30 columns]

In [71]:
random_forest_model = RandomForestClassifier(random_state=42)
random_forest_model.fit(x_train_scaled, y_train)
y_pred_rf = random_forest_model.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
classification_rep_rf = classification_report(y_test, y_pred_rf)
print("Random Forest Model:")
print(f"Accuracy: {accuracy_rf:.2f}")
print(f"Confusion Matrix:\n{conf_matrix_rf}")
print(f"Classification Report:\n{classification_rep_rf}")
print("-" * 50)

			

Random Forest Model:
Accuracy: 0.47
Confusion Matrix:
[[19  0]
 [21  0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.47      1.00      0.64        19
           1       0.00      0.00      0.00        21

    accuracy                           0.47        40
   macro avg       0.24      0.50      0.32        40
weighted avg       0.23      0.47      0.31        40

--------------------------------------------------


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted sam

In [69]:
logistic_regression_model = LogisticRegression(random_state=42)
logistic_regression_model.fit(X_train, y_train)
y_pred_lr = logistic_regression_model.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)
classification_rep_lr = classification_report(y_test, y_pred_lr)
print("Logistic Regression Model:")
print(f"Accuracy: {accuracy_lr:.2f}")
print(f"Confusion Matrix:\n{conf_matrix_lr}")
print(f"Classification Report:\n{classification_rep_lr}")
print("-" * 50)



Logistic Regression Model:
Accuracy: 0.93
Confusion Matrix:
[[17  2]
 [ 1 20]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.89      0.92        19
           1       0.91      0.95      0.93        21

    accuracy                           0.93        40
   macro avg       0.93      0.92      0.92        40
weighted avg       0.93      0.93      0.92        40

--------------------------------------------------


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [67]:
svm_model = SVC(random_state=42)
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
classification_rep_svm = classification_report(y_test, y_pred_svm)
print("Support Vector Machine (SVM) Model:")
print(f"Accuracy: {accuracy_svm:.2f}")
print(f"Confusion Matrix:\n{conf_matrix_svm}")
print(f"Classification Report:\n{classification_rep_svm}")
print("-" * 50)

Support Vector Machine (SVM) Model:
Accuracy: 0.93
Confusion Matrix:
[[18  1]
 [ 2 19]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.92        19
           1       0.95      0.90      0.93        21

    accuracy                           0.93        40
   macro avg       0.93      0.93      0.92        40
weighted avg       0.93      0.93      0.93        40

--------------------------------------------------


In [63]:
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)
classification_rep_knn = classification_report(y_test, y_pred_knn)
print("K-Nearest Neighbors (KNN) Model:")
print(f"Accuracy: {accuracy_knn:.2f}")
print(f"Confusion Matrix:\n{conf_matrix_knn}")
print(f"Classification Report:\n{classification_rep_knn}")


K-Nearest Neighbors (KNN) Model:
Accuracy: 0.93
Confusion Matrix:
[[16  3]
 [ 0 21]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.84      0.91        19
           1       0.88      1.00      0.93        21

    accuracy                           0.93        40
   macro avg       0.94      0.92      0.92        40
weighted avg       0.93      0.93      0.92        40



In [73]:
							# Taking input from the user
print("Please enter values for the features to predict the class:")
feature_names = X.columns.tolist()
user_input = []
for feature in feature_names:
    value = float(input(f"Enter value for {feature}: "))
    user_input.append(value)

# Predicting using the trained model
predicted_class = random_forest_model.predict([user_input])
print(f"The predicted class is: {predicted_class[0]} So it is Fraud .....")
			



Please enter values for the features to predict the class:


Enter value for Time:  9
Enter value for V1:  34
Enter value for V2:  98
Enter value for V3:  37
Enter value for V4:  29
Enter value for V5:  38
Enter value for V6:  94
Enter value for V7:  39
Enter value for V8:  28
Enter value for V9:  56
Enter value for V10:  37
Enter value for V11:  56
Enter value for V12:  48
Enter value for V13:  92
Enter value for V14:  46
Enter value for V15:  36
Enter value for V16:  27
Enter value for V17:  19
Enter value for V18:  50
Enter value for V19:  64
Enter value for V20:  72
Enter value for V21:  12
Enter value for V22:  84
Enter value for V23:  27
Enter value for V24:  19
Enter value for V25:  93
Enter value for V26:  89
Enter value for V27:  90
Enter value for V28:  35
Enter value for Amount:  50225


The predicted class is: 0 So it is Fraud .....
